name: Generate CycloneDX SBOM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install cyclonedx-bom
        run: npm install -g @cyclonedx/bom

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.xml

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4  # Gebruik de nieuwste versie!
        with:
          name: sbom
          path: sbom.xml



































